server:
  port: 8050
spring:
  application:
    name: litchi-comsumer-file-upload
  http:
    multipart:
      max-file-size: 2000Mb      # Max file size，默认1M
      max-request-size: 2500Mb   # Max request size，默认10M
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false #spring boot 1.5 开始，默认为actuator开启了安全保护