server:
  port: 8010
spring:
  application:
    name: litchi-comsumer-movie-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true