server:
  port: 8010
spring:
  application:
    name: litchi-comsumer-movie-ribbon-properties-customizing
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true
ribbon:
  eureka:
    enabled: false
litchi-provider-user:
  ribbon:
    listOfServers: localhost:7900