server:
  port: 8010
spring:
  application:
    name: litchi-comsumer-movie-feign-customizing
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true
logging:
  level:
    org.litchi.comsumer.movie.feign.UserFeignClient: DEBUG