server:
  port: 8010
#  context-path: /ribbon
spring:
  application:
    name: litchi-comsumer-movie-ribbon-with-hystrix
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    health-check-url: ${management.context-path}/health
#    home-page-url: /ribbon
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

management:
  security:
    enabled: false #spring boot 1.5 开始，默认为actuator开启了安全保护