server:
  port: 8181
spring:
  application:
    name: litchi-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lyl616/litchi-springcloud-config.git
          search-paths: /src/main/resources/
  profiles:
    active: prod