server:
  port: 8010
spring:
  application:
    name: litchi-comsumer-movie-ribbon-with-hystrix-propagation
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000