server:
  port: 8010
spring:
  application:
    name: litchi-comsumer-movie-ribbon-properties-customizing
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true
litchi-provider-user:
  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
management:
  security:
    enabled: false #spring boot 1.5 开始，默认为actuator开启了安全保护